spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user
    password: password
  data:
    redis:
      host: localhost
      port: 6379